### PR TITLE
Update Django to 2.2.12 LTS and related changes

### PR DESCRIPTION
**Pull request by frenzymadness**
Basically, this updates this example to Django 2.2.12 (LTS version) and all its dependencies to the latest versions.

There is one big issue: Django >= 2 requires SQLite 3.8.3 but Centos/RHEL 7 contains version 3.7.17 which means that this example will work only of Fedora and Centos/RHEL 8. If we are okay with that, I'll add a note to the readme.

Tested with S2I Python 3 container based on Fedora 31 (Python 3.6):
```
$ s2i build ./ f31/python3 --as-dockerfile Dockerfile.update
$ podman build -f Dockerfile.update -t django-ex:update
$ podman run --rm -it -p 8080:8080  django-ex:update
…
---> Serving application with 'manage.py runserver' ...
WARNING: this is NOT a recommended way to run you application in production!
Consider using gunicorn or some other production web server.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 08, 2020 - 09:56:07
Django version 2.2.13, using settings 'project.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[08/Jun/2020 09:56:31] "GET / HTTP/1.1" 200 27849
```

TODO:

- [ ] Testing in openshift
- [ ] Fix dead links to openshift documentation

Because I have almost zero knowledge about openshift and no access to that, any help with openshift appreciated.

### CODE REVIEW

**Comment by frenzymadness** [comment]
Cc @torsava @hhorak

**Comment by torsava** [comment]
@frenzymadness It's sad that it won't work on CentOS/RHEL7, however, we want people to switch to 8 anyway.

What if we tagged the current version of djangoex (#centos7, #rhel7, #django1), and then from the updated README we can link to one of these tags for people that want to use the old Django version?

**Comment by torsava** [comment]
@hhorak Would you be able to recommend someone to help with testing in openshift and updating the openshift documentation links?

**Comment by frenzymadness** [comment]
> What if we tagged the current version of djangoex (#centos7, #rhel7, #django1), and then from the updated README we can link to one of these tags for people that want to use the old Django version?

Good idea. I'd need commit rights to do that.

> The commit `Recreated app welcome` added a file `welcome/apps.py` but didn't remove any. Is this a new file that's needed, or is it supposed to obsolete some old file(s)?
> 
> So that we don't leave useless files lying around confusing users.

This file is created automatically by Django command `./manage.py startapp welcome`. I've basically deleted the content of this repository and repeated the steps mentioned in the readme so there should be no leftovers ­— only files created by Django or updated code from previous version.

> Besides this, the PR looks good.

Thanks.

**Comment by torsava** [comment]
> Good idea. I'd need commit rights to do that.
> 
> >

@pkubatrh Hi, could you please give @frenzymadness commit rights to this repo?

**Comment by torsava** [comment]
> This file is created automatically by Django command `./manage.py startapp welcome`. I've basically deleted the content of this repository and repeated the steps mentioned in the readme so there should be no leftovers ­— only files created by Django or updated code from previous version.
> 
> >

Ah, perfect. +1

**Comment by torsava** [comment]
@pkubatrh  Hi, could you please give @frenzymadness commit rights to this repo?

**Comment by frenzymadness** [comment]
I am going to create a new branch `1.11.x` from the current master branch and merge this manually to master then with a note in Readme.

**Comment by frenzymadness** [comment]
The new branch for older Django is in: https://github.com/sclorg/django-ex/tree/1.11.x
The last commit adds a note about it.
A follow-up issue for the missing points here is: https://github.com/sclorg/django-ex/issues/152

**Comment by torsava** [comment]
@frenzymadness Nice work!

**Pull request merged**
