### PR TITLE
Upgrade to Django 2.0 and Python 3.6

### PR DESCRIPTION
**Pull request by jpic**
This is just a requirements update after rebase of #115, works fine on openshift v3.9.0+8e3cb9b-8

### CODE REVIEW

**Comment by hhorak** [comment]
Well, this does not work for me with rhscl/python-36-rhel7 image, I get this error when running the built image:
```
#> docker run -ti --rm django2test
---> Migrating database ...
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/django/urls/conf.py", line 17, in include
    urlconf_module, app_name = arg
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/opt/app-root/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/app-root/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/app-root/lib/python3.6/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/opt/app-root/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/app-root/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/app-root/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/app-root/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/app-root/src/project/urls.py", line 14, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "/opt/app-root/lib/python3.6/site-packages/django/urls/conf.py", line 27, in include
    'provide the namespace argument to include() instead.' % len(arg)
django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.
```
I'm not any python nor django expert, so I don't feel like I'm able to investigate more.

**Comment by jpic** [comment]
Hello @hhorak, thanks for your feedback
I used openshift2 a lot but just started learning openshift3, i can fix the python/django errors for sure if i can reproduce them, can you tell me how to reproduce this exactly please ?

**Comment by shellox** [comment]
Hello @jpic and @hhorak,

It did not work for me either with the URLs in the pull request:

I made it work with Openshift 3 when I changed the URLs to the following:

    path('', index),
    path('health', health),
    path('admin/', admin.site.urls),

At least it went through the build process and shows the index page.

**Comment by jpic** [comment]
Yes 79a9f7f uses path too.

**Comment by shellox** [comment]
@jpic my point is:
+    path('/', index),
 +    path('health', health),
 +    path('admin/', include(admin.site.urls)),

didn't work. I got the same error message as you.

But I changed these 3 lines to:
path('', index),
path('health', health),
path('admin/', admin.site.urls),

Now it works for me.

**Comment by frenzymadness** [comment]
I will finish this update in https://github.com/sclorg/django-ex/pull/150

**Pull request closed without merging**
